apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    name: http
  selector:
    app: spring-boot-app
  type: NodePort